# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install Java and Grobid client
RUN apt-get update && apt-get install -y default-jdk
RUN git clone https://github.com/kermitt2/grobid_client_python.git
WORKDIR /app/grobid_client_python
RUN pip install -r requirements.txt

# Run script
CMD ["jupyter", "nbconvert", "--to", "script", "script.ipynb", "--output", "script.py", "&&", "python", "script.py"]
